apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


labels:
  - includeTemplates: true
    pairs:
      app: demo
      project: flink-demo
   

resources:
  - flinkdeployment.yaml
  - service-acccount.yaml
  - rbac.yaml
