apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-app-settings
data:
  NAME: schematic-flink
  NAMESPACE: flink
  FLINK_VERSION: v1_20
  DEV_IMAGE: quay.io/colinchan2025/flink_base:dev
  FLINK_DEPLOY_MODE: application
  SERVICE_ACCOUNT: default
